//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyNine
{
    using System;
    using System.Collections.Generic;
    
    public partial class materials_short_k_import
    {
        public string Наименование_материала { get; set; }
        public string Тип_материала { get; set; }
        public string Количество_в_упаковке { get; set; }
        public string Единица_измерения { get; set; }
        public string Количество_на_складе { get; set; }
        public string Минимальный_возможный_остаток { get; set; }
        public string Стоимость { get; set; }
    }
}
